name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  NODE_VERSION: 18.17.0

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint